plugins {
    id 'com.android.application'
}

android {
    namespace "com.google.ar.core.examples.java.principal"
    compileSdk 34

    viewBinding {
        enabled = true
    }

    defaultConfig {
        applicationId "com.google.ar.core.examples.java.principal"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/native-image/org.mongodb/bson/native-image.properties'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {

    // ARCore para renderização de objetos 3D
    implementation 'com.google.ar:core:1.46.0'

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // ML Kit para reconhecimento de texto
    implementation 'com.google.mlkit:text-recognition:16.0.0'

    // MongoDB Java Reactive Streams Driver
    implementation 'org.mongodb:mongodb-driver-reactivestreams:4.9.1'
    implementation 'org.mongodb:mongodb-driver-sync:4.9.1'
    implementation 'org.mongodb:bson:4.9.1'

    implementation 'de.javagl:obj:0.4.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    // Outras dependências comuns
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.2'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
