plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.chaquo.python'
}

android {
    compileSdkVersion 35

    defaultConfig {
        applicationId "com.google.ar.core.examples.java.principal"
        resourceConfigurations += ["en", "br"]

        minSdkVersion 24
        targetSdkVersion 34
        versionCode 1
        versionName '1.0'

        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }

        python {
            version "3.8"
            pip {
                install "requests"
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    viewBinding {
        enabled = true
    }

    namespace 'com.google.ar.core.examples.java.principal'

    packagingOptions {
        exclude 'META-INF/native-image/org.mongodb/bson/native-image.properties'
    }
}

dependencies {
    // ARCore (Google Play Services for AR) library.
    implementation 'com.google.ar:core:1.46.0'

    // Inclui o ML Kit Text Recognition no projeto
    implementation 'com.google.mlkit:text-recognition:16.0.0'
    implementation 'com.google.mlkit:vision-common:17.3.0'

    // Obj - A simple Wavefront OBJ file loader
    implementation 'de.javagl:obj:0.4.0'

    // Glide - An image loading and caching library for Android
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    // KMongo (MongoDB para Android)
    implementation 'org.litote.kmongo:kmongo:4.4.0'
    implementation 'org.litote.kmongo:kmongo-async:4.4.0'
    implementation 'org.litote.kmongo:kmongo-coroutine:4.4.0'

    // Core AndroidX libraries
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'com.google.android.material:material:1.12.0'


    // Dependência SLF4J
    implementation 'org.slf4j:slf4j-android:1.7.36'

}